name: Java CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Compile Java
        run: javac Main.java

      - name: Create output folder
        run: mkdir -p output

      - name: Move compiled file
        run: mv Main.class output/

      - name: Upload artifact (automation output)
        uses: actions/upload-artifact@v4
        with:
          name: java-build
          path: output/