name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Compile
        run: |
          javac Main.java
          javac TestMain.java

      - name: Run Tests
        run: java TestMain

      - name: Create Deployment Folder
        run: mkdir deploy

      - name: Simulated Deployment
        run: echo Deployment Successful > deploy\result.txt